name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Git version
      run: git --version  # Ensure that Git is installed on the runner

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 1  # Fetch only the latest commit
        
    - name: Debug - Check Git status and remotes
      run: |
        git status
        git remote -v

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install Qt 6
      run: |
        sudo apt-get install -y qt6-base-dev

    - name: Remove existing CMake cache (if any)
      run: |
        rm -rf CMakeCache.txt
        rm -rf CMakeFiles/
        rm -rf build/

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/qt6

    - name: Build with CMake
      run: cmake --build build
