name: Qt Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use 'windows-latest' if you're using Windows runners

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: actions/setup-cmake@v3

      - name: Install Qt
        run: sudo apt-get install qt5-qmake qtbase5-dev

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run Tests (optional)
        run: |
          cd build
          ctest --output-on-failure
